### ISSUE TITLE
Possibly not connecting to MSFS

### ISSUE THREAD

**Issue by Bastocheanoncon** [Fragtality/FenixQuartz#14]
All buttons stuck on 3 dot waiting state. No control in sim.

[PilotsDeck20230307.log](https://github.com/Fragtality/PilotsDeck_FNX/files/10916321/PilotsDeck20230307.log)
[FNX2PLD20230307.log](https://github.com/Fragtality/PilotsDeck_FNX/files/10916995/FNX2PLD20230307.log)
[StreamDeck0.log](https://github.com/Fragtality/PilotsDeck_FNX/files/10916330/StreamDeck0.log)

I feel like I'm one overlooked step/issue away from getting to try out your work.

EDIT: The edits are just re-uploads of logs after most recent attempts to fix.

**Comment by Bastocheanoncon** [comment]
Solved. Every... single... binary... was not being run as admin.

For future troubleshooters:

Stream Deck
Pilot's Deck
FSUIPC7
MSFS 2020
Fenix A320
Pilot's Deck_FNX2PLD

All must be run as admin.

**Comment by Fragtality** [comment]
That is false Information. Non of these require to be run as admin, everything works perfectly well without that.

But when messing around with that setting, it might be that this is required. So the only thing I will consider in the Readme: reinforcing that this FSX/P3D Illness is not required and could lead to Problems if still followed.

Cool that it now works for you, but be aware that you're running on non-normal procedures ;D

**Comment by Bastocheanoncon** [comment]
Of course. To be clear, it is that they all needed to share the same state for me. "Run as admin" or not. As soon as they were uniform in "run as admin" state, it worked. I have to run some of those binaries as admin for other reasons. It started working once all of those matched as far as admin privileges go.

**Comment by Fragtality** [comment]
The Fenix Binary (PilotsDeck_FNX2PLD) does indeed require to be run in the same Elevation as MSFS/Fenix - only then it can access the Process Memory. But that would also work when run under the normal User Elevation.

Did not really test how that influences Connections via SimConnect - maybe SimConnect also requires the same Elevation? But I honestly don't care since I'm happy that this Illness is not needed anymore. ^^
