### ISSUE TITLE
Not working with the recent update

### ISSUE THREAD

**Issue by rickvandijck** [Fragtality/FenixQuartz#15]
Due to the reworked display rendering, FenixQuartz unfortunately doesn't work anymore. 
I'm guessing this request is somewhat unnecessary, but will you be able to update it anytime soon? 

Thanks in advance

**Comment by Fragtality** [comment]
Well, it does work. Made a couple of Tests yesterday, no Issues with the Displays. (Note: still on SU12, and SU13 Beta is not recommended by Fenix)

Only V-Speeds don't work, but I already got them half-way working in the [FenixQuartz-latest.zip](https://github.com/Fragtality/FenixQuartz/blob/master/FenixQuartz-latest.zip)

**Comment by rickvandijck** [comment]
> Well, it does work. Made a couple of Tests yesterday, no Issues with the Displays. (Note: still on SU12, and SU13 Beta is not recommended by Fenix)
> 
> Only V-Speeds don't work, but I already got them half-way working in the [FenixQuartz-latest.zip](https://github.com/Fragtality/FenixQuartz/blob/master/FenixQuartz-latest.zip)

Just launched it again, and works fine now. No clue why it didn't show/output any values yesterday. I simply thought it was caused by the Fenix update. Thanks for the quick reply though :)

**Comment by Fragtality** [comment]
Maybe V2 has some additional/different Memory Locations, but for that I need to encounter that Situation first to go searching ^^
I'll surely monitor it!
