### ISSUE TITLE
Problem interpreting the XPDR live display value.

### ISSUE THREAD

**Issue by alphaleonis** [Fragtality/FenixQuartz#18]
The value of the xpdr output does not contain enough information to re-create the transponder display (when using raw values/LVARs at least). Most of the time it works great, except when a transponder code is entered that starts with one or more zeroes. 

Since only a single number is output, we cannot differentiate between the display containing for example `44--` (where `-` is blank), `044-` or `0044`.  

Also when clearing the display and then entering a zero, the XPDR output becomes the last transponer code set until a non-zero digit (or a fourth zero) is entered.

I think the simplest way would probably be to output four variables, one for each digit. However, looking at the source code I was not able to figure out how to do this, since it seems the raw memory value we get for `xpdrDisplay`  is just a16-bit integer.  So not sure how they actually determine the display value in their code.

**Comment by Fragtality** [comment]
Who exactly is "we"?

**Comment by alphaleonis** [comment]
Apparently a case of poor phrasing.

The first occurence of "we" should probably be replaced with "I", since at least I couldn't figure out how to differentiate between the mentioned cases. But perhaps I'm missing something.

For the second occurence of "we" I was simply referring to the the value received from the call to `AddMemoryValue` for `xpdrDisplay`.

**Comment by Fragtality** [comment]
Ah, okay! Had to make sure you're not one of these greedy Addon-Devs leeching free Support for their Payware Product :wink:

Uhm well, I honestly totally overlooked that (Squawk Codes with leading Zeroes) oO
Though it may be possible to determine that after the Code is complete (just format to 4 digits, adding leading zeros as neccessary), I don't currently see a Way to do that while it is typed. I'll have to look into that.

AddMemoryValue is the wrong Place. It is just storing the Value/Location. The export is done in the UpdateXpdr Function

**Comment by alphaleonis** [comment]
> Ah, okay! Had to make sure you're not one of these greedy Addon-Devs leeching free Support for their Payware Product 😉

Ah, I was a bit confused there at first. But no addon developer here 😀

> AddMemoryValue is the wrong Place. It is just storing the Value/Location. The export is done in the UpdateXpdr Function

Yeah, again, poor phrasing from me 😂 I meant that the original value read from the fenix memory seems to be a 16 bit integer as well. I'm guessing they must have another value somewhere that somehow indicates what is actually shown in the display, or how many numbers are entered.  Guess that might be a bit difficult to find though.

**Comment by Fragtality** [comment]
Thanks for finding that!
I won't pull that, but I will implement it.

But does it really need to be every single Digit? The Deal with Raw-Values was always that Users have to look after formatting & transforming the Values.

**Comment by alphaleonis** [comment]
AFAIK I don't think you can provide strings in lvars. I guess you could encode it as a 32 bit integer with each digit consuming 4 bits, or just skip the digits and just provide the digit count of course. The makes it a bit more complicated on the other side of course, depending on the software in use to provide the actual output, but should be workable as well I guess.

**Comment by Fragtality** [comment]
Well I would export the Digit Count of course, so that Users are able to format the Output as they require it.
Think of the Users building their FCU on Top of the Raw Values - they also just have a Number and need to format it to a certain amount of digits (e.g. heading 1 / 001). It would basically the same, just that the number of digits in the format Function comes from a Variable instead ;)

**Comment by alphaleonis** [comment]
Yes, I'm sure that will suffice.  It will work for my purposes anyway. I guess I'm just more fluent in C# than in Spad.Next or similar softwares, so for me it was easier to do it there, but there will be less maintenance of this software without the single digit feature of course. :)  I'm happy either way.

**Comment by Fragtality** [comment]
Check out the [latest ](https://github.com/Fragtality/FenixQuartz/blob/master/FenixQuartz-latest.zip)Build and if and how it works for you :)

**Comment by alphaleonis** [comment]
Seems to work just great! Thank you for the great work with this 😄
