### ISSUE TITLE
Support for EFIS Baro "Is Std"

### ISSUE THREAD

**Issue by alphaleonis** [Fragtality/FenixQuartz#20]
If it is already possible to the get information on whether the captain/FO baro is "Std" or not from some LVar in the sim I apologize for this request, but I couldn't find any way of reliably getting this info from the in sim variables. 

It seems to be available at the following offsets (according to my somewhat inferior knowledge):
```
{ "BAROFO-1", new MemoryPattern("45 00 46 00 49 00 53 00 20 00 46 00 2F 00 4F 00 20 00 62 00 61 00 72 00 6F 00 20 00 73 00 74 00 61 00 6E 00 64 00 61 00 72 00 64 00") },
{ "BAROCP-1", new MemoryPattern("45 00 46 00 49 00 53 00 20 00 43 00 61 00 70 00 74 00 20 00 62 00 61 00 72 00 6F 00 20 00 73 00 74 00 61 00 6E 00 64 00 61 00 72 00 64") }

// ...
AddMemoryValue("foBaroIsStd", MemoryPatterns["BAROFO-1"], 0xCE, 1, "bool");
AddMemoryValue("cptBaroIsStd", MemoryPatterns["BAROCP-1"], 0xCE, 1, "bool");
```

Any chance we could get these added as well (provided they are correct and not already available elsewhere)?   (If so, let me know if you want a PR)

(Works on my machine)

**Comment by Fragtality** [comment]
Will not be added, as this is already available via Fenix L-Vars and standard A-Vars:
https://kb.fenixsim.com/example-of-how-to-use-lvars

Example:
```lua
function FNX_READ_BARO()
	local unitMode = ipc.readLvar("S_FCU_EFIS1_BARO_MODE")
	local pressure = ipc.readUW(0x0330)
	local offset = 0x5401
	local newvalue = "Std"

	if ipc.readLvar("S_OH_IN_LT_ANN_LT") == 2 then
		newvalue = "8888"
	elseif ipc.readLvar("I_FCU_TRACK_FPA_MODE") == 0 and ipc.readLvar("I_FCU_HEADING_VS_MODE") == 0 then
		newvalue = ""
	elseif ipc.readLvar("S_FCU_EFIS1_BARO_STD")	~= 1 then
		if unitMode == 0 then
			newvalue = string.format("%.0f", pressure * 0.1845585973546601)
			newvalue = string.sub(newvalue, 0,2) .. "." .. string.sub(newvalue, 3)
		else
			newvalue = string.format("%04.0f", pressure * 0.0625)
		end
	end

	ipc.writeSTR(offset, newvalue, 5)
end
```
Offset 0330 should be A-Var KOHLSMAN SETTING MB:1 I think

**Comment by alphaleonis** [comment]
I was not referring to the pressure value itself, since this is indeed readable via the `KOHLSMAN SETTING MB:1` (for the captain's side anyway. I would have expected `KOHLSMAN SETTING MB:2` to be the FO side seting, but it just seems to duplicate the captain's side).

I was referring to whether the display shows the value "Std" or not basically, i.e. if you have pulled the knob.  The code above doesn't work if you pull the knob twice in a row, because the value of `S_FCU_EFIS1_BARO_STD` does not swap between 1 and 0 as one would expect, instead it is incremented by 1 every time you pull the button and decremented by 1 every time you push it.  This means that reading the value of this does not tell me whether "Std" mode is active or not.

Now I discovered you can sort of "hack" it by checking if the `KOHLSMAN SETTING MB:1` is equal to `1013.25` which seems to be the case when "Std" is active. Not sure if you can get to that value manually in another way though.

**Comment by Fragtality** [comment]
Yes you could go for 1013.25 - but that only really works for millibars. For inHg you would not be able to differ between STD and the actual Pressure being 29.92.

And correct, many Buttons work that Way in the Fenix - being relative (incremented, decremented) instead of being absolute.

If you really need to have a "hybrid" Setup where the Baro can be pulled/pushed via Mouse (!) and external Hardware at the same Time (!), then you have to implement a Logic to detect an Increase or Decrease in Value (and program the HW Interface also to increment/decrement the Value). I think testing for even/odd should also work.

Or just let it toggle between 0 and 1 and use only the Hardware to manipulate the Baro - like I do without any Problems ;)

**Comment by alphaleonis** [comment]
I'm too bad at being consistent in my use of my hardware controls, so sometimes I use the mouse. (It's not like I have an entire cockpit built unfortunately).  Anyway, `KOHLSMAN SETTING MB:1` is 1013.25 even when in inHg mode, so it sort of works for now. Except for the fact that it (at least sometimes) seems to be 1013.25 when first launching the Fenix, even though it is not in Std.  So I guess I will have to resort to that, or maintaining my own fork with the above offsets added.  (I understand your reluctance to add more than absolutely necessary due to future maintenance, so no worries).

**Comment by Fragtality** [comment]
I don't have a Cockpit built either, and don't have to use the Mouse at all during Flight 😉 

What is the Issue with building the mentioned Logic (is greater/lower or is odd/even)?

**Comment by Fragtality** [comment]
@alphaleonis 
Check out the latest Devbuild: https://github.com/Fragtality/FenixQuartz/blob/master/FenixQuartz-latest.zip

The (Captain) Baro is not based on Memory-Values, it is just the normal A-Var and Fenix L-Vars that are handled here.
The is Standard Indication works well for me, even with "hybrid" Usage 😅

**Comment by alphaleonis** [comment]
Yep, this seems to work excellent. 😄  Thanks for adding this!

**Comment by Framac23** [comment]
Hi.
It seems that tle LVars "FNX2PLD_isisBaro" and "FNX2PLD_isisStd" are no longer working:
I think these variables were given by FenixQuartz, but now they have always the same value.
Is this a bug  or am I doing something wrong?
Thanks :)

**Comment by Fragtality** [comment]
Consistently not working? That would be really strange, especially if everything else works.

Maybe you just had bad luck and had the very seldom Situation that the Value could not be found in Memory?

**Comment by Framac23** [comment]
Sorry, it was my fault.
When I updated to this version I didn't see that the Lvars were disabled and only the offsets were working.
After activating the Lvasr everything was working fine.
Thank you very much for this interface, which really helps a lot.
Regards
FraMac

**Comment by Fragtality** [comment]
Yep it was - it is stated in the Readme that the Config File is overwritten with an Update 😅 

The next Version will have the Installer from Fenix2GSX and with that also keeping the Settings after an Update 😉
