### ISSUE TITLE
Issue on V-Speeds not read by Quartz

### ISSUE THREAD

**Issue by ChrisPUA320** [Fragtality/FenixQuartz#21]
Hi, I found out that the V Speeds are not read by Fenix Quartz although the Vars are present. I always get a VR of "32761" and "0" with the others. Any help on this issue is appreciated...(Var-Names are changed to "FNX320_", but all others working fine)
rgds
Chris
![2023-09-03_11h17_53](https://github.com/Fragtality/FenixQuartz/assets/113291887/ea6aea29-b9a9-4f7c-8978-1c71df99a102)
![2023-09-03_11h18_02](https://github.com/Fragtality/FenixQuartz/assets/113291887/d2632a27-dd4b-40f7-9f9e-e1b16ec9f7ff)

**Comment by Fragtality** [comment]
The L-Vars are always created, so that does not mean anything 😉 

And you are using the latest DevBuild ([FenixQuartz-latest.zip](https://github.com/Fragtality/FenixQuartz/blob/master/FenixQuartz-latest.zip))?
Sure they not stable yet, because the V-Speeds are harder to catch with V2, but the DevBuilds should at least sometimes/mostly catch the Speeds.

**Comment by ChrisPUA320** [comment]
I am using the latest build. But the Vars stay at zero unfortunately…Am 03.09.2023 um 14:13 schrieb Fragtality ***@***.***>:﻿
The L-Vars are always created, so that does not mean anything 😉
And you are using the latest DevBuild (FenixQuartz-latest.zip)?
Sure they not stable yet, because the V-Speeds are harder to catch with V2, but the DevBuilds should at least sometimes/mostly catch the Speeds.

**Comment by Fragtality** [comment]
How is it with  the current dev Build?
https://github.com/Fragtality/FenixQuartz/blob/master/FenixQuartz-latest.zip

It is a semi-automatic Process now:
- Enter V-Speeds (does not play a role if something else is entered or not in the Perf Page)
- Hold PERF Button until orange Dash (on the MCDU) lights up
- If valid V-Speeds where found, the RDY Indicator will light up
