### ISSUE TITLE
Automatically start do not work !

### ISSUE THREAD

**Issue by SMN204** [Fragtality/FenixQuartz#22]
I added this to my FSUIPC7.ini

[Programs]
RunIf1=READY,KILL,F:\Game Setup\MSFS 2020 My\My Fenix A320\Add on\Pilot Monitoring Callouts for the FENIX A320\FenixQuartz\FenixQuartz v1.1\FenixQuartz.exe
<a href="https://fastpic.org/view/122/2023/1020/1579618bc5b4f5f1752e2dfc50db4554.jpeg.html" target="_blank"><img src="https://i122.fastpic.org/thumb/2023/1020/54/1579618bc5b4f5f1752e2dfc50db4554.jpeg" border="0"></a>

FenixQuartz do not start automatically  with FSUIPC7 :-(

P.S  Sorry! I have FSUIPC7 started before fenixA320 starts, when FSUIP7 starts after Fenix start - the "FenixQuartz" start aumatically !
And there should be no spaces in the path name, as I understand it.

**Comment by Fragtality** [comment]
Wow, ehrm, I don't know if there is a Limit to the Path-Length in FSUIPC 😅 

Well, I let FSUIPC auto-start with the Sim, which in turn means Fenix2GSX is also started some time after that.

Hmm, spaces! Could be, did not check the FSUIPC Readme about that.
