### ISSUE TITLE
all v speed 0

### ISSUE THREAD

**Issue by stratte89** [Fragtality/FenixQuartz#24]
hey guys, 

i'm trying to get it to work the whole day but i couldn't make it. 

![image](https://github.com/Fragtality/FenixQuartz/assets/101955267/555371d8-b2e7-4d42-85ba-d832fc0c09ca)
![image](https://github.com/Fragtality/FenixQuartz/assets/101955267/5269e29f-ff6a-48b7-b132-c25c697638f9)

The V speed show up as 0 in aao. Also is there a way to get N1 of the Engines as well as the Rotation speed of the APU?

**Comment by Fragtality** [comment]
The V-Speeds got broken with V2 Block 1 and the last 1.1 Release of FenixQuartz.

Try that Build: https://www.mediafire.com/file/celtfrsizlmfx1y/FenixQuartz-Installer-v1.2.0.exe/file
But note that the Process is now manual:
- Enter Perf Data
- Hold the PERF Key on the MCDU until the Orange Dash lights up and then release it
- When valid V-Speeds where detected you see the RDY light briefly show up

There is a Failback that scans for the V-Speeds when the Plane started moving, but I strongly recommend to that Procedure. Then you can be sure that the Scan was made and if valid Speeds where found.

**Comment by Fragtality** [comment]
And NO: N1/Rotation Values not planned. It is already enough for a Plane that does not allow anything.

**Comment by stratte89** [comment]
Thank you for your quick response. I installed it and set it to start with fsuipc. Where do I find the config to output Lvars? I just loaded in the sim and put in some v speed, then i held t
![image](https://github.com/Fragtality/FenixQuartz/assets/101955267/e7a0ef2a-3d2d-4cc9-a7db-02381dd927b9)
he perf key but nothing happend.

**Comment by Fragtality** [comment]
Great to hear :)
Note that I still have to do some long-term Test on the latest Change to the V-Speeds. It worked reliable before and then suddenly encountered Situations where it would not work anymore. So I can just hope the latest Change now is finally ready to release.

**Comment by stratte89** [comment]
Thanks for your effort, rlly great job :)
