### ISSUE TITLE
Reading of FLEX Temp

### ISSUE THREAD

**Issue by ChrisPUA320** [Fragtality/FenixQuartz#25]
Thanks for your great work on reading the values needed for the FENIX. Will it be possible to read the FLEX Temp given in the MCDU as well?

best regards
Chris

**Comment by Fragtality** [comment]
Hmm, maybe. Would need to look into this to see if it's possible.

**Comment by ChrisPUA320** [comment]
Anything new on this issue ?

rgds
Chris

**Comment by Fragtality** [comment]
Added in 1.5.0
