### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by dcherrie** [Fragtality/FenixQuartz#27]
There is no documentation on how to uninstall / completely remove the program.

**Comment by rickvandijck** [comment]
Run the installer, click remove/uninstall

**Comment by Fragtality** [comment]
As described by rickvandijck.

Isn't documented since a red "Remove" Button does not need much Explanation 😉

**Comment by dcherrie** [comment]
The most common way of removing software is through Add or remove programs which it wasn't there so that's why I asked.
